<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Monthly Report — {{ $monthLabel }}</title>
    <style>
        body { font-family: Helvetica, Arial, sans-serif; color: #1f2937; font-size: 12px; }
        h1 { font-size: 20px; margin-bottom: 0; color: #047857; }
        .subtitle { color: #6b7280; margin-top: 4px; margin-bottom: 24px; }
        .summary { width: 100%; border-collapse: collapse; margin-bottom: 28px; }
        .summary td { width: 33.33%; padding: 12px; border: 1px solid #e5e7eb; text-align: center; }
        .summary .label { display: block; color: #6b7280; font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; }
        .summary .value { display: block; font-size: 18px; font-weight: bold; margin-top: 4px; }
        .income .value { color: #047857; }
        .expense .value { color: #b91c1c; }
        h2 { font-size: 14px; margin-top: 24px; margin-bottom: 8px; border-bottom: 2px solid #e5e7eb; padding-bottom: 4px; }
        table.rows { width: 100%; border-collapse: collapse; }
        table.rows th, table.rows td { padding: 6px 8px; border-bottom: 1px solid #f3f4f6; text-align: left; }
        table.rows th { color: #6b7280; font-size: 10px; text-transform: uppercase; }
        table.rows td.amount, table.rows th.amount { text-align: right; }
        .empty { color: #9ca3af; font-style: italic; padding: 8px 0; }
        .footer { margin-top: 32px; color: #9ca3af; font-size: 10px; }
    </style>
</head>
<body>
    <h1>{{ $family->name }}</h1>
    <p class="subtitle">Monthly Report — {{ $monthLabel }} · Currency: {{ $family->currency }}</p>

    <table class="summary">
        <tr>
            <td class="income">
                <span class="label">Income</span>
                <span class="value">{{ number_format($totalIncome, 2) }}</span>
            </td>
            <td class="expense">
                <span class="label">Expense</span>
                <span class="value">{{ number_format($totalExpense, 2) }}</span>
            </td>
            <td>
                <span class="label">Net</span>
                <span class="value">{{ number_format($net, 2) }}</span>
            </td>
        </tr>
    </table>

    <h2>Income by Category</h2>
    @if ($income->isEmpty())
        <p class="empty">No approved income recorded this month.</p>
    @else
        <table class="rows">
            <thead>
                <tr><th>Category</th><th class="amount">Transactions</th><th class="amount">Total</th></tr>
            </thead>
            <tbody>
                @foreach ($income as $row)
                    <tr>
                        <td>{{ $row['category'] }}</td>
                        <td class="amount">{{ $row['count'] }}</td>
                        <td class="amount">{{ number_format($row['total'], 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <h2>Expense by Category</h2>
    @if ($expense->isEmpty())
        <p class="empty">No approved expenses recorded this month.</p>
    @else
        <table class="rows">
            <thead>
                <tr><th>Category</th><th class="amount">Transactions</th><th class="amount">Total</th></tr>
            </thead>
            <tbody>
                @foreach ($expense as $row)
                    <tr>
                        <td>{{ $row['category'] }}</td>
                        <td class="amount">{{ $row['count'] }}</td>
                        <td class="amount">{{ number_format($row['total'], 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <p class="footer">Generated by HifzMaal on {{ $generatedAt->format('d M Y, H:i') }}. Only approved transactions are included.</p>
</body>
</html>
