<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Zakat Certificate — {{ $calculation->hijri_year }} AH</title>
    <style>
        body { font-family: Helvetica, Arial, sans-serif; color: #1f2937; font-size: 12px; }
        .header { text-align: center; border-bottom: 3px solid #047857; padding-bottom: 16px; margin-bottom: 24px; }
        .header h1 { font-size: 22px; color: #047857; margin-bottom: 4px; }
        .header p { color: #6b7280; margin: 0; }
        .badge { display: inline-block; margin-top: 10px; padding: 4px 14px; border-radius: 999px; font-size: 11px; font-weight: bold; }
        .badge.paid { background: #d1fae5; color: #047857; }
        .badge.due { background: #fef3c7; color: #92400e; }
        table.figures { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        table.figures td { padding: 8px 10px; border-bottom: 1px solid #f3f4f6; }
        table.figures td.label { color: #6b7280; }
        table.figures td.value { text-align: right; font-weight: bold; }
        table.figures tr.total td { border-top: 2px solid #e5e7eb; font-size: 13px; }
        h2 { font-size: 14px; margin-top: 24px; margin-bottom: 8px; border-bottom: 2px solid #e5e7eb; padding-bottom: 4px; }
        table.rows { width: 100%; border-collapse: collapse; }
        table.rows th, table.rows td { padding: 6px 8px; border-bottom: 1px solid #f3f4f6; text-align: left; }
        table.rows th { color: #6b7280; font-size: 10px; text-transform: uppercase; }
        table.rows td.amount, table.rows th.amount { text-align: right; }
        .empty { color: #9ca3af; font-style: italic; }
        .disclaimer { margin-top: 28px; padding: 12px; background: #f9fafb; border-left: 3px solid #d1d5db; color: #6b7280; font-size: 10px; }
        .footer { margin-top: 20px; color: #9ca3af; font-size: 10px; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Zakat Record — {{ $family->name }}</h1>
        <p>Hijri Year {{ $calculation->hijri_year }} AH · Calculated {{ $calculation->calculation_date->format('d M Y') }}</p>
        <span class="badge {{ $calculation->isFullyPaid() ? 'paid' : 'due' }}">
            {{ $calculation->isFullyPaid() ? 'Fully Paid' : 'Payment Outstanding' }}
        </span>
    </div>

    <table class="figures">
        <tr>
            <td class="label">Total Zakatable Assets</td>
            <td class="value">{{ number_format((float) $calculation->total_assets, 2) }} {{ $family->currency }}</td>
        </tr>
        <tr>
            <td class="label">Nisab Threshold ({{ $calculation->nisab_type }})</td>
            <td class="value">{{ number_format((float) $calculation->nisab_amount, 2) }} {{ $family->currency }}</td>
        </tr>
        <tr>
            <td class="label">Zakatable Amount</td>
            <td class="value">{{ number_format((float) $calculation->zakatable_amount, 2) }} {{ $family->currency }}</td>
        </tr>
        <tr class="total">
            <td class="label">Zakat Due (2.5%)</td>
            <td class="value">{{ number_format((float) $calculation->zakat_due, 2) }} {{ $family->currency }}</td>
        </tr>
        <tr>
            <td class="label">Zakat Paid</td>
            <td class="value">{{ number_format((float) $calculation->zakat_paid, 2) }} {{ $family->currency }}</td>
        </tr>
        <tr>
            <td class="label">Remaining</td>
            <td class="value">{{ number_format((float) $calculation->zakat_remaining, 2) }} {{ $family->currency }}</td>
        </tr>
    </table>

    <h2>Payment History</h2>
    @if ($payments->isEmpty())
        <p class="empty">No payments recorded yet for this year.</p>
    @else
        <table class="rows">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Recipient</th>
                    <th>Type</th>
                    <th class="amount">Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($payments as $payment)
                    <tr>
                        <td>{{ $payment->payment_date->format('d M Y') }}</td>
                        <td>{{ $payment->recipient->name ?? $payment->recipient_name ?? '—' }}</td>
                        <td>{{ ucfirst($payment->type) }}</td>
                        <td class="amount">{{ number_format((float) $payment->amount, 2) }} {{ $family->currency }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <p class="disclaimer">
        This document is a record of Zakat calculated and paid through HifzMaal for your own
        record-keeping. It is not a religious ruling — nisab thresholds and calculation logic are
        provided for convenience only and should be verified with a qualified Islamic scholar.
    </p>

    <p class="footer">Generated by HifzMaal on {{ $generatedAt->format('d M Y, H:i') }}.</p>
</body>
</html>
